### ISSUE TITLE
Use clusters-plotter on points data

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/napari-clusters-plotter#103]
It would be super nice to use the clusters plotter on points data. Implementation could be relatively straightforward as points layers also have a `points.features` attribute where measurements could live. The resulting cluster ID could be stored in an additional column, just as we already do it with labels layers.

The color of points can be changed as follows (I think it max be the same as for labels data):
```Python
features = {'values': [0, 0.5, 1, 1.5, ....]}
viewer.add_points(points_data, color_map='hot', face_color='values', features=features)
```

**Comment by Cryaaa** [comment]
Implemented in https://github.com/BiAPoL/napari-clusters-plotter/pull/229
