### ISSUE TITLE
Fix dimension reduction tests

### ISSUE THREAD

**Issue by Cryaaa** [BiAPoL/napari-clusters-plotter#110]
In #109 we had to comment out the testing function: `test_call_to_function` in `test_dimension_reduction.py` to fix tests timing out on mac OS. This decreased code coverage and we should look at what caused this and how we can fix this but for now we will leave the test commented out to push the next release.

**Comment by lazigu** [comment]
These tests were added back and passed in #150, so this issue can be closed.
