### ISSUE TITLE
Selection is reset in measurements-list

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#114]
In the clustering widget (and potentially also other places), the selection in the measurements-list is reset and that's hard to see for the user. 

To reproduce:
* Load data (e.g. blobs), segment it, appyly measurements.
* Use the dimensionality reduction widget, e.g. UMAP
* Use the clustering widget:
  * Select UMAP0 and UMAP1 only
  * Cluster, e.g. K-Means

After clustering, all measurments will be selected. If the user wants to also use HDBSCAN, they first have to select UMAP0 and UMAP1 again - and that's not obvious.

Potential solution: When updating the measurements-list, keep the selection.

**Comment by Cryaaa** [comment]
@haesleinhuepf thanks for bringing that to our attention. I have also noticed that this behaviour is quite annoying and I'll look into it!
