### ISSUE TITLE
Cluster IDs in space is incorrent/current frame is not highlighted for a timelapse in version 0.5.2

### ISSUE THREAD

**Issue by lazigu** [BiAPoL/napari-clusters-plotter#131]
Hi, all!

There is a bug in version 0.5.2 (not sure about 0.5.1, I haven't tested that one). However, in 0.5.0 it works perfectly.
In the image below, on the left - version 0.5.2, and on the right - 0.5.0 with exactly the same data, reg props file and manual cluster. The current timepoint is not highlighted in the plot, and manual clustering in the generated cluster_ids_in_space is wrong.
![image](https://user-images.githubusercontent.com/52177660/187082914-57f937e5-61f9-44ef-83d2-6dd9082ea6ca.png)

It would be nice if somebody could confirm that they also encounter this bug.
I cannot dig deeper right now, so I will continue using the older version and fix this when I have more time unless somebody is faster :)

**Comment by haesleinhuepf** [comment]
Yeah, that's unfortunate. I recommend relabeling sequentially per timepoint and adding a section in the documentation.

> dictionary mapping instead of pyclesperanto 
I would like to veto the dictionary mapping because there is no single algorithm on earth that allow us post-processig these LUT-mapped label images. This strategy appears to me as a dead-end.

**Comment by lazigu** [comment]
> I would like to veto the dictionary mapping because there is no single algorithm on earth that allow us post-processig these LUT-mapped label images. This strategy appears to me as a dead-end.

Good, then I will just make the requirements for the uploaded files clearer in the documentation.
Do you think it makes sense to implement a check whether labelling is sequential/missing labels are still in the _csv_ file and issue a warning if not, so the user would be warned that visualisation is incorrect?

**Comment by haesleinhuepf** [comment]
Yes, maybe we should implement such a check. I'm afraid it will take some time and thus, we need to be careful where to put it. So that it's not executed again and again all the time...
