### ISSUE TITLE
`Plot measurements` should be in the Visualization menu in the tools

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/napari-clusters-plotter#137]
Headline says it all - I find it confusing that this widget is there.

**Comment by haesleinhuepf** [comment]
Fine with me. We can have menus in multiple places. Example:
https://github.com/haesleinhuepf/napari-process-points-and-surfaces/blob/b1eee0567e9b879e8c873d7fc3c0a01752df039c/napari_process_points_and_surfaces/__init__.py#L321

Would you mind sending a PR @jo-mueller ?

Thanks!
Robert

**Comment by jo-mueller** [comment]
Sure thing
