### ISSUE TITLE
moved menus - update documentation

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#164]
I was just cleaning up the `Tools > Measurement` menu because it became a bit crowded. There are now two new menus `Measurement maps` and `Measurement tables`. 

![image](https://user-images.githubusercontent.com/12660498/212553069-17f8e754-cd34-4d65-a8af-c7b732ae006e.png)

![image](https://user-images.githubusercontent.com/12660498/212553086-f7e1c1f6-56cf-4577-beb3-286f1f3f6a62.png)

Todo:
* We should update the clusters plotter documentation to hint users to `Tools > Measurement tables` instead of `Tools > Measurement` (this should be easy)

Optional todo:
* We _could_ create another menu `Tools > Measurement post-processing` and put `Dimensionality reduction (ncp)` and `Clustering (ncp)` in there. I'm not sure if this would be helpful. Thus, I leave it for discussion :-)

**Comment by lazigu** [comment]
I like the idea of having dimensionality reduction and clustering widgets in "Tools > Measurement post-processing" menu. I think it makes a lot of sense to separate them from the rest. Thanks, Robert @haesleinhuepf!
