### ISSUE TITLE
Supporting multi-FOV and timelapse stacks

### ISSUE THREAD

**Issue by mimuelle** [BiAPoL/napari-clusters-plotter#18]
Hi,
What an absolutely amazing tool! Saw it yesterday and couldn't wait to test it! :) 
I first tested it on a single FOV, which worked beautifully (feature extraction, plotting, interactive highlighting of cells, clustering, UMAP).

I mostly work with multi-FOV and timelapse images though, so I wanted to try this as well and realized that (if I'm not mistaken) the features are extracted 'per label_id' across all FOVs/timepoints and then summed up. Are you planning to support multi-FOV/timelapse data as well? Would be amazing of course, but don't know how far up your priority list that would be..
Maybe one could introduce unique identifiers for each object across all images? Instead of using the label_ids which are usually 0-n, restarting on each image again. 
Anyways, super cool and looking forward to using this tool a lot!

**Comment by lazigu** [comment]
Hi @mimuelle,

Sorry for the delayed reply. 
First of all, thank you so much for such kind feedback! I'm so happy to hear that you have already tried out the plugin and it worked nicely for a single FOV.

Secondly, I completely agree that it would be amazing to have support for timelapse images in the plugin. We also work with timelapse data. The image from the documentation example gif is originally 3D + time. And you are right, features are extracted per label id across all time points. However, another problem that we experience is that during segmentation labels are switched i.e. there is no cell tracking, and the same cell can have different labels across time points. Therefore, with the dataset I tested the plugin, I couldn't consider one cell a unique object until I have the correct segmentation of cells. 
However, I will definitely work on this. I should start with a simpler timelapse dataset that doesn't have so many objects/cells. But I cannot say yet when such a feature could be expected to be released. 
Again, I really appreciate the feedback, great to know what kind of features would be useful for the users!

Best,
Laura

**Comment by mimuelle** [comment]
Hi Laura,
Thanks for your reply! 
Maybe it would make sense not to start with a timelapse but just a multi-FOV dataset? Then at least the tracking of cells over images is not necessary, which could eventually be included later on. Because for both cases I guess label_ids have to be handled independently from image to image, therefore requiring some additional "unique identifier".
I'm really looking forward to any updates on that and best of luck with further working on this cool plug-in! :-)

Best,
Micha

**Comment by lazigu** [comment]
Closed in #77
