### ISSUE TITLE
Make plotting work programmatically.

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#181]
I'd like to control plotting in the GUI from Python. Therefore a method `PlotterWidget.run()` or `PlotterWidget.plot()` calling [this code](https://github.com/BiAPoL/napari-clusters-plotter/blob/8a5acb72dd6e9866dd26e1335ecc4b31e1693f8b/napari_clusters_plotter/_plotter.py#L159) would be necessary. Currently, I can only control plotting using this workaround ([full exmaple](https://github.com/BiAPoL/napari-clusters-plotter-example-notebooks/blob/main/notebooks/plotting_in_napari.ipynb)):

```
plotter_widget.plot_x_axis.setCurrentText("area")
plotter_widget.plot_y_axis.setCurrentText("mean_intensity")

# workaround to click run button programmatically
layout = plotter_widget.layout()
widgetitem = layout.itemAt(layout.count()-2)
run_button = widgetitem.widget().layout().itemAt(0).widget()
run_button.clicked.emit()
```

Optional: We could also implement two or three functions like `plotter_widget.set_x_axis(column_name:str)` which checks if the passed column name exists and throws an error otherwise.

**Comment by zoccoler** [comment]
I believe if we replace the base plotter by the on in napari-matplotlib as suggested in #85 and do something similar to the [FeatureScatterWidget](https://github.com/matplotlib/napari-matplotlib/blob/308134b6dc568d88b7ac81d83fba25af8d2ed6fa/src/napari_matplotlib/scatter.py#L111), this would become much easier. There you would do something like `plotter_widget._draw()` or `plotter_widget.draw()`

**Comment by lazigu** [comment]
Hi both,

So I played around with this, and we currently can do plotting programmatically like this:

![image](https://user-images.githubusercontent.com/52177660/222757205-bcb3ffcf-a8c5-4f88-8fa4-1df842bdff4a.png)

The only thing missing is a check whether given measurements actually exist, otherwise, Keyerror is thrown. I will send a small PR implementing this check.
