### ISSUE TITLE
Multiple extension for Measurement -> Plot Measurement / load from csv

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#189]
Hi,

first of all, thank for your great plugin! I would like to use it within the TomoTwin workflow ( https://tomotwin-cryoet.readthedocs.io/en/stable/ ). To give you a very short introduction: TomoTwin is for the localization of Proteins in cellular Tomograms (cryo-ET). It was trained to organize the content (e.g proteins) of those tomograms according shape similarity. It is pretrained on 120 different proteins and generalizes well to new proteins.  There are two workflows, but I will only talk about the clustering workflow, because this is where I would like to use your plugin:

1. Embed the whole tomogram using a sliding window (37x37x37, stride 2) . 
 - Example A: A tomogram with size 512x512x200 produces  4.644.808 embeddings
 - Example B: A tomogram with size 1024 x 1440 x 250 produces 37.106.264 enbeddings
3. Calculate a 2D umap of those embeddings
4. Identify clusters in this umap (so far we also used a lasso tool)
5. Calculate the center of those clusters and use it as reference for further picking.

This is how I use your plugin:
1. A script creates a separate label volume where each embedding (position) gets a unique label
2. A script create a .csv with the umap of the complete dataset which can then be loaded by the measurement tool
3. Circle clusters

Its absolutely fantastic to have a direct feedback where the circled positions are. Great stuff!

But now I need to extend Measurement -> Plot Measurement tool in multiple ways:
1. The umap is totally overplotted. That why you hardly can identify clusters within the umap. I did not find a way to modify the visualization parameters from napari, but  I found the respective numbers that I need to change in the code. There are several heuristics how you come up with your plotting parameters. What about having a separate dialog for changing these values?
![image](https://user-images.githubusercontent.com/1113977/223366487-e1dd53fd-3218-495b-b846-a005a9415891.png)
2. Also regarding overplotting: It probably would make sense, to allow the user to only use a subsample for plotting, but applying the lasso region to the complete dataset. That would probably also make the plotting much faster, which is right now very slow.
3. Reading the csv file of example B is not possible because it requires too much memory. I noticed that you are using pandas read_csv in https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/master/napari_skimage_regionprops/_load_csv.py#L16 - it will use by default float64 which is I guess not necessary for virtually all projects. What about using float32 or maybe even float16? Ideally, this would be an option you can change prior reading.
5. After I circled some of the clusters, I would need to save the respective clustering results. I don't see a way to do that? I would like to add an option for saving this but wondering where you want to have such an extension.
6. As soon you circled one clusters, it interprets the remaining points as a second cluster and all get visualized, which makes it very hard to identify your selected clusters:
![image](https://user-images.githubusercontent.com/1113977/223373436-9d492278-f126-453f-beaa-b02338c7a911.png)
I already found a quick hack by changing the cluster label 0 to -1 making noise labels but idk if that's the way you would like to see it implemented. Anyway, it would be nice if one could specify unselected points as background and don't visualize them.
7. I would love to selected labels in the label volume and see them highlighted within the plot.

I know these are and should be multiple issues, but I first would like to discuss with you how to proceed.

Best,
Thorsten

**Comment by thorstenwagner** [comment]
HI @lazigu !

Thanks for your swift reply. I will open separate issue for 1, 2 and 5.

I will work on 5 first as I think it's nice and easy issue to begin with.

I keep this issue open for further discussions about 3 and 6?

We gonna checkout your solution for 4. That sounds pretty much like a solution. 

Best,
Thorsten

**Comment by GavinR1** [comment]
I agree for point 4 this should be enough, we can add the cluster ID to the full embeddings and then do our calculations from there. 

+1 for point 6, in a lot of our real world datasets something like this would be extremely helpful to identify the location of certain features in the umap.

**Comment by lazigu** [comment]
Thanks, @thorstenwagner for opening those issues.

Regarding 6, we had this feature removed in #80 because it was disturbing the interaction with data in 3D. However, I assume for 2D data it could be easily re-enabled. One thing to note, labels have to be selected one by one, it is not possible to use something like the lasso tool to select multiple objects at once.

**Comment by lazigu** [comment]
Yes, I can also imagine that that data point would be very hard to spot. Maybe additional highlighting by making the spot bigger should be introduced then, similarly to what we have for highlighting the current frame of the timelapse data. 

If you wanted to try the old implementation we had of this feature, you need version 0.4.0 or lower of the plugin. I think because you are not working with timelapse data, that version should not be missing any crucial features. However, plotting would be even less optimal there because no dynamic change of data point sizes and transparency depending on the number of data points was implemented yet.

**Comment by thorstenwagner** [comment]
Regarding point 3 I opened a pull request:

https://github.com/haesleinhuepf/napari-skimage-regionprops/pull/68

With those changes, combined with the 2d histogram, I can now work with datasets as big as 32 millions entries.

**Comment by thorstenwagner** [comment]
Regarding 6:

I think we will not bring it back into this plugin. It was quite easy to add this functionality using an external plugin:

```python
    def get_event(viewer, event):
        global circle
        data_coordinates = label_layer.world_to_data(event.position)
        val = label_layer._get_value(data_coordinates)
        umap_coordinates = umap.loc[umap['label']==val,['umap_0','umap_1']]

        center = umap_coordinates.values.tolist()[0]
        if circle is not None:
            circle.remove()
        circle = Circle(tuple(center), 1, fill=False, color='r')
        plotter_widget.graphics_widget.axes.add_patch(circle)
        plotter_widget.graphics_widget.draw_idle()
```

![image](https://user-images.githubusercontent.com/1113977/224720543-67b12a83-fec9-46e2-8174-802f922c9b95.png)

As I'm only interested in the rough position within the umap, a circle with fixed diameter is enough for me.

That's quite special for our use case I guess, so if you don't need it won't put efforts into adding this to your plugin.

**Comment by lazigu** [comment]
> Regarding 6:
> 
> I think we will not bring it back into this plugin. It was quite easy to add this functionality using an external plugin:
> 
> As I'm only interested in the rough position within the umap, a circle with fixed diameter is enough for me.
> 
> That's quite special for our use case I guess, so if you don't need it won't put efforts into adding this to your plugin.

Great that you found a workaround! 

Should this issue then be closed because I think all the relevant points were split into separate issues?

**Comment by thorstenwagner** [comment]
Can be closed!

Thanks for being so open to my changes.

Best,
Thorsten
