### ISSUE TITLE
Add options to modify plots 

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#190]
This issue is a sub-issue of #189 : 

The umap is totally overplotted in case of datasets with many points. You can hardly identify clusters within the umap. 

![image](https://user-images.githubusercontent.com/1113977/223402060-58ac2da5-f5bc-43c8-b536-0547bc299476.png)

I did not find a way to modify the visualization parameters from napari, but I found the respective numbers that I need to change in the code. There are several heuristics how you come up with your plotting parameters. What about having a separate dialog for changing these values?

**Comment by zoccoler** [comment]
Hi @thorstenwagner ,

Thanks for creating this issue! Indeed it is hard to visualize too many points.
Do you think it could be related to #148 ?

**Comment by thorstenwagner** [comment]
Using heatmaps is one of several options to reduce overplotting issues. So yes, it is related.

I would suggest that each plotting option (scatter, heatmap) provides a setup function, that opens a dialog where you change the respective plotting parameters.  The different plotting options (scatter, heatmap) would need to be decoupled somehow and just called by the PlottingWidget? Right now, the PlottingWidget is tightly coupled with the MplCanvas, that would probably need to be changed?

Let me know what you think :-)

Best,
Thorsten
