### ISSUE TITLE
Use 2D histogram lasso selector for big datasets

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#195]
Related to #190

I modified the lasso selection tool to work with 2D histograms from numpy:

```python
import pandas as pd
import numpy as np
import numpy.random
import matplotlib.pyplot as plt
from matplotlib.widgets import LassoSelector
from matplotlib.path import Path
from matplotlib.widgets import PolygonSelector
from matplotlib.patches import Polygon



class SelectFromCollection:
    def __init__(self, ax, full_data):
        self.ax = ax
        self.canvas = ax.figure.canvas

        self.xys = full_data

        self.lasso = LassoSelector(ax, onselect=self.onselect)
        self.ind = []

    def onselect(self, verts):
        path = Path(verts)
        self.ind = np.nonzero(path.contains_points(self.xys))[0]
        p = Polygon(verts, facecolor = 'red',alpha=0.5)
        self.ax.add_patch(p)
        
        self.canvas.draw_idle()

    def disconnect(self):
        self.lasso.disconnect_events()
        self.canvas.draw_idle()

pth = "tiltseries_rec_embeddings_umap.csv"

dat = pd.read_csv(pth)[['umap_0','umap_1']]


x = dat['umap_0']
y = dat['umap_1']

heatmap, xedges, yedges = np.histogram2d(x, y, bins=400)
extent = [xedges[0], xedges[-1], yedges[0], yedges[-1]]

plt.clf()
plt.imshow(heatmap.T, extent=extent, origin='lower')

ax = plt.gca()

full_data=dat.to_numpy()
selector = SelectFromCollection(ax, full_data)
plt.show()
```

The dataset I use can be found here:
https://owncloud.gwdg.de/index.php/s/fTAFAUL10QjqsWP

Its very performant with 4.5 million datapoints:

![cluster_selection](https://user-images.githubusercontent.com/1113977/223663592-5a1103fc-2f68-478d-9b92-b7f3490a1a6d.gif)

I will now try to integrate into the plotter.

**Comment by thorstenwagner** [comment]
I just tested it with 37 million datasets. Its also very fast.

**Comment by lazigu** [comment]
Amazing! Thanks a lot for working on this!

**Comment by zoccoler** [comment]
That looks awesome! 🤩 
We just need to check if this works with the visualization back in the images and it should be all good!

**Comment by thorstenwagner** [comment]
> Amazing! Thanks a lot for working on this!

Thanks for making this plugin ;-) Happy to contribute!

![image](https://user-images.githubusercontent.com/1113977/223676388-961c42f2-ef94-4b17-8fe8-a34f5da94caf.png)

Works like a charm :-)

**Comment by thorstenwagner** [comment]
See #196 for the implementation.
