### ISSUE TITLE
Use `color` dict instead of recalculate labels 

### ISSUE THREAD

**Issue by Czaki** [BiAPoL/napari-clusters-plotter#21]
Use color `dict` instead of calculating new labels data.  

https://github.com/BiAPoL/napari-clusters-plotter/blob/5e90688096e5dcb82e65c4ebaec40de2ec41857c/napari_clusters_plotter/_plotter.py#L378-L384

Labels layer allow to provide coloring as `{0: 'black', 1: "red", 2: "blue", 3: "red" ...}` Which updating is much faster than recalculationg whole labels data. 

example: https://github.com/4DNucleome/PartSeg/blob/dedd823837e419839328f5526aec350f25934502/package/PartSeg/common_gui/napari_image_view.py#L442

**Comment by Cryaaa** [comment]
Hey @Czaki,
thank you for your feedback! implementing this method of visualisation did indeed speed up the visualisation of clusters, especially when in the 2D view where it removed all of the computing time!
