### ISSUE TITLE
Standardize frame axis position for timelapse

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/napari-clusters-plotter#220]
Currently, frame is taken as the first axis of the `current_step` of the viewer.
If data with dimension > 4 is loaded, then the frame information is wrong.

We could standardize how axes order with (..., time, z, y, x) and get `current_step` as index `-4` instead of `0`.

**Comment by haesleinhuepf** [comment]
Hi @zoccoler ,

can you elaborate in which scenario this causes a problem? I'm just thinking: there might be other napari plugins where assume `current_step[0]` corresponds to time...

**Comment by zoccoler** [comment]
Hi @haesleinhuepf ,

OK, I jumped too early to conclusions. There might also be plugins where time is not expected as the first dimension. What I think we need is some sort of convention or a way to tell users/developers the expected axes order and/or an input that can help the plugin properly interpret that. For example, I am trying to integrate 5D FLIM data and it was not clear where the time axis should go.

Besides, images from different file formats may follow different axes orders, there are discussions on how to know that, like [here](https://forum.image.sc/t/reading-czi-file-in-python/39768/1). One option would be to do what these libraries do and ask for dims order as a sequence of strings, maybe something for [napari-time-slicer](https://github.com/haesleinhuepf/napari-time-slicer)?

Another option, more easily done for the clusters plotter, could be to at least state in the documentation that we expect the following axes order (time, ..., z, y, x) and single channel per image layer. What do you think?

**Comment by lazigu** [comment]
I would also like to add a minor comment: Marcelo's labels data was standard shape what ncp expects (4D), and only because he also had opened intensity image (5D), and since we look at napari viewer's sliders and not actually at data shape in the frame_changed method, the time was not correctly visualized in the plot

**Comment by zoccoler** [comment]
Thanks @lazigu , that actually better explains the problem 😅
