### ISSUE TITLE
Expose `frame_changed` method ?

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/napari-clusters-plotter#242]
Hi all,

I was wondering if we could expose the `frame_changed` method defined [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/4c2c20ecf513bab7f13db8695e6b9caae5861726/napari_clusters_plotter/_plotter.py#L349). 
If we do that, I could provide a solution for [this issue](https://github.com/zoccoler/napari-flim-phasor-calculator/issues/19) and we could potentially close #220 .

I am proposing changes in #221 to address this. Do you agree with this suggestion?

Best,
Marcelo

**Comment by Cryaaa** [comment]
Hey @zoccoler,
I was just looking through this and am wondering how the proposed change of exposing the function changes anything? As far as I can see the frame is still set as the first dimension [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/standardize_frame_axis/napari_clusters_plotter/_plotter.py#:~:text=self.frame%20%3D%20self.viewer.dims.current_step%5B0%5D) and [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/standardize_frame_axis/napari_clusters_plotter/_plotter.py#:~:text=frame%20%3D%20event.value%5B0%5D)? I am also wondering in terms of my own timelapse data if you guys have decided on a convention on where the time axis should be?

**Comment by zoccoler** [comment]
Hi @Cryaaa,
So regarding the clusters-plotter itself, nothing should change with this, but while we don't have a different approach than just grabbing the first axis, exposing this method would allow a plotter subclass to manipulate this callback.
For example, I think I can manipulate the event before calling the superclass method, but I don't know an easy way to do this if the method is not exposed (not sure if this was intentional).

**Comment by Cryaaa** [comment]
@zoccoler,
Ahh I see, well in that case I don't see anything wrong with exposing the function. Unfortunately I don't remember why I didn't expose it, so maybe just thoroughly test it but otherwise I would give the green light from my end!
