### ISSUE TITLE
Resetting zoom after selection of manual clustering

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#251]
Hi,

with the PR https://github.com/BiAPoL/napari-clusters-plotter/pull/214 it did not reset zoom after selecting a cluster.

With the recent release it does it again. So something broke it. Any idea what change might be responsible?

Best,
Thorsten

**Comment by thorstenwagner** [comment]
Found a fix. As soon I'm allowed to open a PR, I will do it :-)

**Comment by haesleinhuepf** [comment]
done in #254
