### ISSUE TITLE
Add me as developer

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#253]
Hi,

@haesleinhuepf 

would it be possible that I get added as developer for that repo so that I can contribute PRs more easily?

Best,
Thorsten

**Comment by haesleinhuepf** [comment]
Absolutely! I just sent you an invite. You'll have `write` access. If you need more, let me know! :-)

**Comment by thorstenwagner** [comment]
Perfect :-) Thanks. Tomorrow I will open the PR for the zoom issue.
