### ISSUE TITLE
Cluster plotter does not work with napari 0.4.18

### ISSUE THREAD

**Issue by thorstenwagner** [BiAPoL/napari-clusters-plotter#258]
See:

https://github.com/napari/napari/issues/6077

We run into the issue because we convert the cluster image to `uint64`:

https://github.com/BiAPoL/napari-clusters-plotter/blob/main/napari_clusters_plotter/_utilities.py#L239

It works perfectly with `uint32`.

Shall we wait for fix in napari or shall we change it?

Best,
Thorsten

**Comment by haesleinhuepf** [comment]
I vote for changing to uint32. Can you send a PR? I'll merge it and deploy.

Thanks!

**Comment by thorstenwagner** [comment]
Done:
https://github.com/BiAPoL/napari-clusters-plotter/pull/259

**Comment by thorstenwagner** [comment]
Should be fixed now!
