### ISSUE TITLE
UMAP does not work if table contains `inf` values

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/napari-clusters-plotter#262]
When the table contains `inf`, either `StandardScaler` [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/96b8ad9b9e06b41c830f2eb69648636a05def0a7/napari_clusters_plotter/_dimensionality_reduction.py#L511) or `umap` [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/96b8ad9b9e06b41c830f2eb69648636a05def0a7/napari_clusters_plotter/_dimensionality_reduction.py#L610) raise exceptions and the widgets does not work, and does not give any feedback to the user. This occurs because of the `try` `except` around this whole part, for instance [here](https://github.com/BiAPoL/napari-clusters-plotter/blob/96b8ad9b9e06b41c830f2eb69648636a05def0a7/napari_clusters_plotter/_dimensionality_reduction.py#L671).

**Comment by thorstenwagner** [comment]
Probably should be closed? Reopen If I'm wrong.
