### ISSUE TITLE
Label image disappears when performing clustering on timelapse data

### ISSUE THREAD

**Issue by stefanhahmann** [BiAPoL/napari-clusters-plotter#269]
Steps to reproduce:

1. Fresh installation of Napari following the instructions of https://biapol.github.io/blog/mara_lampert/getting_started_with_mambaforge_and_python/readme.html
2. Import label_image.tif contained in [label_image.zip](https://github.com/BiAPoL/napari-clusters-plotter/files/12717466/label_image.zip) (zip file contains file label_image.tif, which github did not allow to upload directly)

![label_image_import](https://github.com/BiAPoL/napari-clusters-plotter/assets/10515534/39d61e00-c5bf-43d0-ab3f-131d0c093eec)

The same label may occur in multiple frames.

3. Load measurements contained in 
[measurements.csv](https://github.com/BiAPoL/napari-clusters-plotter/files/12717476/measurements.csv) using Tools > Measurements > Load from CSV

![load_measurements](https://github.com/BiAPoL/napari-clusters-plotter/assets/10515534/3d8ae972-172c-4636-8ca8-b83b1644b78e)

The same label may occur in multiple frames. However, the combination label-frame is unique.

4. When plotting two features, e.g. Branch Sinousity and Branch displacement and making a selection, the original label image label turns black (which is unexpected) and the id layer does not really show the results.

![ncp](https://github.com/BiAPoL/napari-clusters-plotter/assets/10515534/61d7456b-ec40-4cd8-8dd6-5287fb6c0a5a)

When using the 2D-view (i.e. multiple slices per timepoint), the selection performed in the cluster plotter widget seems to be shown correct. However, the original label image is still black.

It is a bit unclear to me, if the provided data is not sufficient or if there actually is a bug in Napari Cluster Plotter

**Comment by zoccoler** [comment]
Hi @stefanhahmann !

A quick thing I could notice is that you have a label `0` in the table. The `0` usually refers to the background, so I think you should avoid having that. Maybe you have to increment all labels. This may be at least part of the problem.

To better investigate that, you could check the checkbox "Show selected" on the top-left. This should allow you to check which row of the table correspond to which object, like shown in the first gif [here](https://github.com/haesleinhuepf/napari-skimage-regionprops#napari-skimage-regionprops-nsr). I am not sure if this works with time-lapse data, but I would expect it does.

**Comment by stefanhahmann** [comment]
> Hi @stefanhahmann !
> 
> A quick thing I could notice is that you have a label `0` in the table. The `0` usually refers to the background, so I think you should avoid having that. Maybe you have to increment all labels. This may be at least part of the problem.

Thanks for pointing this out. The label `0` caused the problem. After incrementing everything by `1` (i.e. the labels in the image and the labels in the corresponding table), it works as expected:

![ncp](https://github.com/BiAPoL/napari-clusters-plotter/assets/10515534/dc510302-552b-4df9-8398-04646083afae)

However, the effect that the label image disappears after the cluster plotter has been used for the first time, still feels like a bug to me.

> To better investigate that, you could check the checkbox "Show selected" on the top-left. This should allow you to check which row of the table correspond to which object, like shown in the first gif [here](https://github.com/haesleinhuepf/napari-skimage-regionprops#napari-skimage-regionprops-nsr). I am not sure if this works with time-lapse data, but I would expect it does.

Thanks for the hint. I can confirm that this works for timelapse data.

**Comment by stefanhahmann** [comment]
I close this issue in favor of: https://github.com/BiAPoL/napari-clusters-plotter/issues/271
