### ISSUE TITLE
Allow U-Map to run in parallel to increase performance

### ISSUE THREAD

**Issue by stefanhahmann** [BiAPoL/napari-clusters-plotter#273]
When performing dimensionality reduction using U-Map (cf. e.g. https://www.youtube.com/watch?v=qZ8KDrgL1Ro) the computation can take very long to large (>100.000 points) datasets (>5 minutes).

The reason is that the U-Map is not run in parallel mode:
![grafik](https://github.com/BiAPoL/napari-clusters-plotter/assets/10515534/005068e1-69d5-4e62-bf2b-d8320dd6934e)

While this makes sure that results are reproducible, it would be nice, to have a checkbox that allows the user to between slower performance and reproducible results and quicker performance and not exactly reproducible (but similar) results.

**Comment by haesleinhuepf** [comment]
Hint: we deactivated parallel execution because it crashed when called from Jupyter:
- https://github.com/BiAPoL/napari-clusters-plotter/issues/169

Maybe it's possible to detect if we run from within napari and then enable parallel execution.

**Comment by stefanhahmann** [comment]
Thanks for the advice. I did not see the optional checkbox to enable multithreading when running napari from command line. But now I found it.

![grafik](https://github.com/BiAPoL/napari-clusters-plotter/assets/10515534/9c30ccd6-0d2c-4041-97a0-51c245863b7a)
