### ISSUE TITLE
Do clustering across layers

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/napari-clusters-plotter#275]
Hi all,

I was wondering whether it could be possible to extent the clustering/visualization feature to data beyond single layers. Imagine, the same set of features has been measured on a set of `N` images. If al of these are loaded into a viewer into `N` different layers, all measured features could - in a future version - be loaded into the plotter widget simultaneously. Selecting a feature in the plotter could then highlight them across all `N` layers which would be supercool for high(er) throughput experiments.

Challenges: 
- The gallery view would be ideal for this - but it would also put the image and its respective cluster map side by side rather than on top of each other
- The layer selection would have to be removed and replaced by getting the currently selected layer(s) in the viewer, for instance.

Solutions:
- I think napari 0.5.0 will support something like grouping layers, the release is, to my knowledge, scheduled for some time early next year. The functionality should already be present though on the napari main branch, so it could be worthwile to already think about it.

**Comment by Cryaaa** [comment]
I really like this idea! I'm guessing though that napari 0.50 breaks quite a bit of other stuff in the plugin though? If so we could prepare by trying to make NCP work with the new requirements

**Comment by jo-mueller** [comment]
Very likely. Among the changes for 0.5.0 that were presented last week at the CZI plugin grantee meeting, they announced to stop supporting npe1 plugins, which would go for this one as well. 

--> will create a new issue

**Comment by jo-mueller** [comment]
@Cryaaa Support for this is added in PR https://github.com/BiAPoL/napari-clusters-plotter/pull/327 and will then come with 0.9.0 along with a major redesign of all functionalities :)

If you find the time, have a look at the current state, feedback is always welcome
