### ISSUE TITLE
Test Failing due to make_napari_viewer

### ISSUE THREAD

**Issue by Cryaaa** [BiAPoL/napari-clusters-plotter#277]
Hello Everyone,
It seems that the test are failing on all new PRs and I think I have found out where the errors are coming from and why some PRs are not failing. It seems to be in some tests the napari viewer is generated with this line:

    viewer = make_napari_viewer(strict_qt=True)

[see here](https://github.com/BiAPoL/napari-clusters-plotter/blob/cbf1a49485b17f55eb5496ff80aa3cd4fd522e9a/napari_clusters_plotter/_tests/test_dimension_reduction.py#L49C5-L49C48) but in other tests strict_qt is not set to any value (so my guess is it defaults to False). Does anyone know why we set this variable and if it is needed? I think @lazigu introduced it a while back to fix some tests apparently but I don't know if we still need it..

**Comment by jo-mueller** [comment]
Is this still up to date? If no, I would close this issue 👍

**Comment by Cryaaa** [comment]
I don't think this is up to date anymore, so it can be closed!
