### ISSUE TITLE
Set up automatic release on PyPi

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/napari-clusters-plotter#299]
We should update the [`test_and_deploy.yaml`](https://github.com/BiAPoL/napari-clusters-plotter/blob/main/.github/workflows/test_and_deploy.yml) to support automatic releases of the plugin through PyPi. For that, we should change the packaging inLine 115 to use 

```
python -m build .
`´`

rather than the use of bdist (`python setup.py sdist bdist_wheel`). We need an API token of the repos owner on PyPi, though.

**Comment by haesleinhuepf** [comment]
Thanks for adding a link to a page where the process is explained. let me just add another potentially useful resource: https://medium.com/@VersuS_/automate-pypi-releases-with-github-actions-4c5a9cfe947d

**Comment by Cryaaa** [comment]
I was trying to see if I can add this functionality but it seems that I cannot look at the repository settings since I am not the owner of the repository (I'm guessing @lazigu or @haesleinhuepf is?). Can this access be changed?

**Comment by jo-mueller** [comment]
@Cryaaa I have access to the repository secrets but there's no API token there. It has to be generated by someone who has access to release process on PyPi.

**Comment by haesleinhuepf** [comment]
I made you admin @Cryaaa

**Comment by jo-mueller** [comment]
Cool. I'll send a PR to update the github action for release to the latest standard and @Cryaaa can pass me the API token to be added as a repository secret. The release on github  should then trigger the automated  upload to PyPi.

**Comment by Cryaaa** [comment]
> Cool. I'll send a PR to update the github action for release to the latest standard and @Cryaaa can pass me the API token to be added as a repository secret. The release on github should then trigger the automated upload to PyPi.

Thanks for taking care of this! I’ll get you the API key on Monday because I’m quite busy this weekend hence my inactivity the past few days..

**Comment by Cryaaa** [comment]
@jo-mueller, I have just added the PYPI API token as a secret to the repository so now most things should be in place! If you need me to take care of anything else please let me know!
