### ISSUE TITLE
Supported layer types in documentation

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#301]
According to the current documentation, only label layers are supported. I recommend updating documentation before #281 

* [ ] List supoorted layer types
* [ ] Explain how to derive measurements for each layer type / list plugins which can do this
* [ ] Add at least one screenshot or screencast showing how to process a surface (because that's a cool new feature that should be highlighted)
* [ ] Add example data for new layer types so that people can try it out

**Comment by Cryaaa** [comment]
Hey @zoccoler!
That would be awesome if you could take care of this. I have an example dataset which I created for testing which uses the napari process points and surfaces package which I could send to you. Maybe we could add it as an example notebook? For the points layer I also have a very basic example which I used which just converts cells to points

**Comment by Cryaaa** [comment]
I have now added some example data for [surfaces](https://github.com/BiAPoL/napari-clusters-plotter/tree/main/example_data/surface_data) and [points](https://github.com/BiAPoL/napari-clusters-plotter/tree/main/example_data/points_data) which can be found using the links!

**Comment by zoccoler** [comment]
Thanks!! I am working on the docs now
