### ISSUE TITLE
Avoid using Labels.color

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/napari-clusters-plotter#307]
With napari 0.4.19, this warnings pops up after manually selecting a cluster

`FutureWarning: Labels.color is deprecated since 0.4.19 and will be removed in 0.5.0, please set Labels.colormap directly with an instance of napari.utils.colormaps.DirectLabelColormap instead.!`

It may be solved by replacing at least [this line](https://github.com/BiAPoL/napari-clusters-plotter/blob/5e937dc8c3347b6557a88d0fd730038182ec628b/napari_clusters_plotter/_plotter.py#L819), [this line](https://github.com/BiAPoL/napari-clusters-plotter/blob/5e937dc8c3347b6557a88d0fd730038182ec628b/napari_clusters_plotter/_plotter.py#L859) and [this line](https://github.com/BiAPoL/napari-clusters-plotter/blob/5e937dc8c3347b6557a88d0fd730038182ec628b/napari_clusters_plotter/_plotter.py#L877) with something like:

`layer_in_viewer.colormap= self.visualized_layer.colormap`

and

`"colormap": DirectLabelColormap(color_dict=cmap_dict),`

This needs to be tested.

**Comment by gboscagli** [comment]
Hi all,
I'm using the Napari-SpatialData plugin (napari v.0.4.19.post1) obtaining the same Warning message. My data points in Napari are not colored, they remain uniformely grey. Is there a way to set the colormap on-the-fly or some other adjustments I can do? From #308 I saw that this remains an issue in Napari >=0.5.0.

**Comment by zoccoler** [comment]
> Hi all, I know I'm probably a bit off-topic. I'm encountering the same Warning message using another Napari plugin (Napari-SpatialData). I have napari v.0.4.19.post1. My data points in Napari are not colored, they remain uniformely grey. To your knowledge, is there a way to set the colormap on-the-fly or some other adjustments I can do? From #308 I saw that this remains an issue in Napari >=0.5.0.

Hi @gboscagli !
This issue is because the Labels layer in napari>=0.5.0 does not have a `.color` attribute anymore. The napari developers left a deprecation warning so that plugin developers could update their plugins in case they were using that attribute.
In your case, it would be best to create the issue directly in the Napari-SpatialData plugin, so that developers there can work on the issue on their code.

**Comment by gboscagli** [comment]
> Hi @gboscagli ! This issue is because the Labels layer in napari>=0.5.0 does not have a `.color` attribute anymore. The napari developers left a deprecation warning so that plugin developers could update their plugins in case they were using that attribute. In your case, it would be best to create the issue directly in the Napari-SpatialData plugin, so that developers there can work on the issue on their code.

That's what I did, I'm in contact with Napari-SpatialData developers and they indeed confirmed it's on the roadmap. By the way, I updated Napari to 0.5.0 and the problem remains, so in the case of SpatialData it's probably matter of internal metadata.

Thanks for the response!

**Comment by zoccoler** [comment]
Fixed via #308
