### ISSUE TITLE
Use pre-commit to increase code quality

### ISSUE THREAD

**Issue by Czaki** [BiAPoL/napari-clusters-plotter#31]
There is a really nice tool to perform multiply automated code quality tests (and apply auto-fixes if possible) before committing.

It is called pre-commit. https://pre-commit.com/

An example of its usage you could be found in:
1) napari:  https://github.com/napari/napari/blob/main/.pre-commit-config.yaml
2) superqt https://github.com/napari/superqt/blob/main/.pre-commit-config.yaml
3) PartSeg https://github.com/4DNucleome/PartSeg/blob/develop/.pre-commit-config.yaml

The plus of this tool is that it keeps the configuration of lines in one file and forces the same version of linter for all contributors. 

There is also CI service https://pre-commit.ci/ which runs these checks separately, so even if the contributor does not activate pre-commit on his side it will be checked. 

## List of nice hooks:

* `black` https://github.com/psf/black -  code formater, no conflicts in a merge, because of different formating. When one is familiar with the tool, then it helps to keep code readable without creating own styling rules.
* `isort` https://github.com/PyCQA/isort -  sorting imports. One order of imports, similar to blake. 
* `pyupgrade` use the most modern (and fastest) python language constructions. 
* `flake8` https://github.com/PyCQA/flake8 - find typical bugs in python code. 
*  `napari-plugin-checks` https://github.com/tlambert03/napari-plugin-checks - nice checker for most common bugs when creating napari plugin. 
```
  - repo: https://github.com/tlambert03/napari-plugin-checks
    rev: v0.2.0
    hooks:
        - id: napari-plugin-checks
 ```

For more hooks, you could check linked configurations and visit https://pre-commit.com/hooks.html. 

It could be a little annoying on begin, but it will help you in the future.

**Comment by lazigu** [comment]
Hi @Czaki, thanks a lot for this, I will look into it!
