### ISSUE TITLE
Cannot select points layer

### ISSUE THREAD

**Issue by rhornb** [BiAPoL/napari-clusters-plotter#314]
Hey all, 

thanks for creating this amazing tool! 

I tried to reproduce [this example notebook](https://github.com/BiAPoL/napari-clusters-plotter/blob/69714c25fc0750a3223fca29f8cbfdf2d232daea/example_data/points_data/loading_points_data_example.ipynb) for points layers. However, I cannot select the points layer in the drop-down menu in any of the napari-clusters-plotter functionalities. Any clue what could cause this? Here is a screenshot of the example dataset:

![image](https://github.com/BiAPoL/napari-clusters-plotter/assets/80632600/27806be3-da45-4914-966a-75928bc51f29)

For label images everything works as it should. 

I am working on a mac M1 in this environment:
`
# Name                    Version                   Build  Channel
alabaster                 0.7.16             pyhd8ed1ab_0    conda-forge
annotated-types           0.6.0              pyhd8ed1ab_0    conda-forge
aom                       3.8.2                h73e2aa4_0    conda-forge
app-model                 0.2.6              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.4              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
autopep8                  2.1.0              pyhd8ed1ab_0    conda-forge
aws-c-auth                0.7.17               hb47d15a_2    conda-forge
aws-c-cal                 0.6.11               hbce485b_0    conda-forge
aws-c-common              0.9.15               h10d778d_0    conda-forge
aws-c-compression         0.2.18               h53e3db5_3    conda-forge
aws-c-event-stream        0.4.2                he461af8_8    conda-forge
aws-c-http                0.8.1               h0afc28a_10    conda-forge
aws-c-io                  0.14.7               h6254544_6    conda-forge
aws-c-mqtt                0.10.3               hd66502f_4    conda-forge
aws-c-s3                  0.5.7                h4907f8a_1    conda-forge
aws-c-sdkutils            0.1.15               h53e3db5_3    conda-forge
aws-checksums             0.1.18               h53e3db5_3    conda-forge
aws-crt-cpp               0.26.6               hfb53d2e_4    conda-forge
aws-sdk-cpp               1.11.267             h01edc24_6    conda-forge
babel                     2.14.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
blosc                     1.21.5               hafa3907_1    conda-forge
bokeh                     3.4.1              pyhd8ed1ab_0    conda-forge
brotli                    1.1.0                h0dc2134_1    conda-forge
brotli-bin                1.1.0                h0dc2134_1    conda-forge
brotli-python             1.1.0            py39h840bb9f_1    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h10d778d_5    conda-forge
c-ares                    1.28.1               h10d778d_0    conda-forge
c-blosc2                  2.14.4               h0ae8482_1    conda-forge
ca-certificates           2024.2.2             h8857fd0_0    conda-forge
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charls                    2.4.2                he965462_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
cloudpickle               3.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1            py39h0ca7971_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
cython                    0.29.37          py39hd253f6c_0    conda-forge
cytoolz                   0.12.3           py39ha09f3b3_0    conda-forge
dask                      2024.4.2           pyhd8ed1ab_0    conda-forge
dask-core                 2024.4.2           pyhd8ed1ab_0    conda-forge
dask-expr                 1.0.12             pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                h0dc2134_0    conda-forge
debugpy                   1.8.1            py39hd253f6c_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deprecated                1.2.14             pyh1a96a4e_0    conda-forge
distributed               2024.4.2           pyhd8ed1ab_0    conda-forge
docstring_parser          0.16               pyhd8ed1ab_0    conda-forge
docutils                  0.21.1             pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h73e2aa4_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h5bb23bf_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.51.0           py39ha09f3b3_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
freetype-py               2.4.0              pyhd8ed1ab_0    conda-forge
fsspec                    2024.3.1           pyhca7485f_0    conda-forge
gettext                   0.22.5               h5ff76d1_2    conda-forge
gettext-tools             0.22.5               h5ff76d1_2    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
giflib                    5.2.2                h10d778d_0    conda-forge
glib                      2.80.0               h81c1438_6    conda-forge
glib-tools                2.80.0               h49a7eea_6    conda-forge
glog                      0.7.0                h31b1b29_0    conda-forge
gst-plugins-base          1.24.1               h12dd0d4_1    conda-forge
gstreamer                 1.24.1               h7c243d7_1    conda-forge
hdbscan                   0.8.33           py39h5b4affa_5    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hsluv                     5.0.4              pyhd8ed1ab_0    conda-forge
icu                       73.2                 hf5e326d_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
imagecodecs               2024.1.1         py39ha20330a_6    conda-forge
imageio                   2.34.1             pyh4b66e23_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
in-n-out                  0.2.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.3             pyh3cd1d5f_0    conda-forge
ipython                   8.12.0             pyhd1c38e8_0    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.3              pyhd8ed1ab_0    conda-forge
joblib                    1.4.0              pyhd8ed1ab_0    conda-forge
jsonschema                4.21.1             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.12.0           py39h6e9494a_0    conda-forge
jxrlib                    1.1                  h10d778d_3    conda-forge
kiwisolver                1.4.5            py39h8ee36c8_1    conda-forge
krb5                      1.21.2               hb884880_0    conda-forge
lazy_loader               0.4                pyhd8ed1ab_0    conda-forge
lcms2                     2.16                 ha2f27b4_0    conda-forge
lerc                      4.0.0                hb486fe8_0    conda-forge
libabseil                 20240116.1      cxx17_hc1bcbd7_2    conda-forge
libaec                    1.1.3                h73e2aa4_0    conda-forge
libarrow                  15.0.2           h965e444_3_cpu    conda-forge
libarrow-acero            15.0.2           ha0df490_3_cpu    conda-forge
libarrow-dataset          15.0.2           ha0df490_3_cpu    conda-forge
libarrow-flight           15.0.2           h41520de_3_cpu    conda-forge
libarrow-flight-sql       15.0.2           hb2e0ddf_3_cpu    conda-forge
libarrow-gandiva          15.0.2           h6ac0def_3_cpu    conda-forge
libarrow-substrait        15.0.2           hb2e0ddf_3_cpu    conda-forge
libasprintf               0.22.5               h5ff76d1_2    conda-forge
libasprintf-devel         0.22.5               h5ff76d1_2    conda-forge
libavif16                 1.0.4                he6768c5_2    conda-forge
libblas                   3.9.0           22_osx64_openblas    conda-forge
libbrotlicommon           1.1.0                h0dc2134_1    conda-forge
libbrotlidec              1.1.0                h0dc2134_1    conda-forge
libbrotlienc              1.1.0                h0dc2134_1    conda-forge
libcblas                  3.9.0           22_osx64_openblas    conda-forge
libclang-cpp15            15.0.7          default_h7151d67_5    conda-forge
libclang13                18.1.3          default_h0edc4dd_0    conda-forge
libcrc32c                 1.1.2                he49afe7_0    conda-forge
libcurl                   8.7.1                h726d00d_0    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.20                 h49d49c5_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 h10d778d_2    conda-forge
libevent                  2.1.12               ha90c15b_1    conda-forge
libexpat                  2.6.2                h73e2aa4_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgettextpo              0.22.5               h5ff76d1_2    conda-forge
libgettextpo-devel        0.22.5               h5ff76d1_2    conda-forge
libgfortran               5.0.0           13_2_0_h97931a8_3    conda-forge
libgfortran5              13.2.0               h2873a65_3    conda-forge
libglib                   2.80.0               h81c1438_6    conda-forge
libgoogle-cloud           2.22.0               h651e89d_1    conda-forge
libgoogle-cloud-storage   2.22.0               ha67e85c_1    conda-forge
libgrpc                   1.62.2               h384b2fc_0    conda-forge
libhwloc                  2.10.0          default_h1321489_1000    conda-forge
libhwy                    1.1.0                h7728843_0    conda-forge
libiconv                  1.17                 hd75f5a5_2    conda-forge
libintl                   0.22.5               h5ff76d1_2    conda-forge
libintl-devel             0.22.5               h5ff76d1_2    conda-forge
libjpeg-turbo             3.0.0                h0dc2134_1    conda-forge
libjxl                    0.10.2               hb3b1962_0    conda-forge
liblapack                 3.9.0           22_osx64_openblas    conda-forge
libllvm14                 14.0.6               hc8e404f_4    conda-forge
libllvm15                 15.0.7               hbedff68_4    conda-forge
libllvm16                 16.0.6               hbedff68_3    conda-forge
libllvm18                 18.1.3               hbcf5fad_0    conda-forge
libnghttp2                1.58.0               h64cf6d3_1    conda-forge
libogg                    1.3.4                h35c211d_1    conda-forge
libopenblas               0.3.27          openmp_hfef2a42_0    conda-forge
libopus                   1.3.1                hc929b4f_1    conda-forge
libparquet                15.0.2           h7cd3cfe_3_cpu    conda-forge
libpng                    1.6.43               h92b6c6a_0    conda-forge
libpq                     16.2                 ha925e61_1    conda-forge
libprotobuf               4.25.3               h4e4d658_0    conda-forge
libre2-11                 2023.09.01           h81f5012_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libsqlite                 3.45.3               h92b6c6a_0    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libthrift                 0.19.0               h064b379_1    conda-forge
libtiff                   4.6.0                h129831d_3    conda-forge
libutf8proc               2.8.0                hb7f2c08_0    conda-forge
libvorbis                 1.3.7                h046ec9c_0    conda-forge
libwebp-base              1.4.0                h10d778d_0    conda-forge
libxcb                    1.15                 hb7f2c08_0    conda-forge
libxml2                   2.12.6               hc0ae0f7_2    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               18.1.3               hb6ac08f_0    conda-forge
llvmlite                  0.42.0           py39he5a6977_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.3            py39h91cfb08_0    conda-forge
lz4-c                     1.9.4                hf0c8a7f_0    conda-forge
magicgui                  0.8.2              pyhd8ed1ab_1    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5            py39ha09f3b3_0    conda-forge
matplotlib-base           3.8.4            py39h7070ae8_0    conda-forge
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.7            py39h6be1789_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.3.0                hfd7a639_4    conda-forge
mysql-libs                8.3.0                ha9146f8_4    conda-forge
napari                    0.4.17          pyh275ddea_0_pyqt    conda-forge
napari-clusters-plotter   0.7.3              pyhd8ed1ab_0    conda-forge
napari-console            0.0.9              pyh9208f05_0    conda-forge
napari-plugin-engine      0.2.0              pyhd8ed1ab_2    conda-forge
napari-skimage-regionprops 0.10.1             pyhd8ed1ab_0    conda-forge
napari-svg                0.1.10             pyhd8ed1ab_0    conda-forge
napari-tools-menu         0.1.19             pyhd8ed1ab_0    conda-forge
napari-workflows          0.2.10             pyhd8ed1ab_0    conda-forge
ncurses                   6.4.20240210         h73e2aa4_0    conda-forge
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
npe2                      0.7.5              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 hea0b92c_0    conda-forge
nss                       3.98                 ha05da47_0    conda-forge
numba                     0.59.1           py39hb7f44fa_0    conda-forge
numcodecs                 0.12.1           py39h110ca85_0    conda-forge
numpy                     1.23.5           py39hdfa1d0c_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h7310d3a_0    conda-forge
openssl                   3.2.1                hd75f5a5_1    conda-forge
orc                       2.0.0                hf146577_1    conda-forge
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2            py39haf03413_0    conda-forge
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
pcre2                     10.43                h0ad2156_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.3.0           py39h9dabb2a_0    conda-forge
pint                      0.23               pyhd8ed1ab_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
pooch                     1.8.1              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
prompt_toolkit            3.0.42               hd8ed1ab_0    conda-forge
psutil                    5.9.8            py39ha09f3b3_0    conda-forge
psygnal                   0.11.0             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   15.0.2          py39h8a9fa87_3_cpu    conda-forge
pyarrow-hotfix            0.6                pyhd8ed1ab_0    conda-forge
pycodestyle               2.11.1             pyhd8ed1ab_0    conda-forge
pyconify                  0.1.6              pyhd8ed1ab_0    conda-forge
pydantic                  1.10.14          py39ha09f3b3_0    conda-forge
pydantic-compat           0.1.2              pyhd8ed1ab_0    conda-forge
pydantic-core             2.18.1           py39hcf47035_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.12             pyhca7485f_0    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pyproject_hooks           1.0.0              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9           py39h3dce684_5    conda-forge
pyqt5-sip                 12.12.2          py39hb11a7c1_5    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.19          h7a9c478_0_cpython    conda-forge
python-build              1.2.1              pyhd8ed1ab_0    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.9                      4_cp39    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1            py39hd01001f_1    conda-forge
pyyaml                    6.0.1            py39hdc70f33_1    conda-forge
pyzmq                     26.0.2           py39hffc4518_0    conda-forge
qt-main                   5.15.8              hecaf5c3_21    conda-forge
qtconsole-base            5.5.1              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
rav1e                     0.6.6                h7205ca4_2    conda-forge
re2                       2023.09.01           hb168e87_2    conda-forge
readline                  8.2                  h9e318b2_1    conda-forge
referencing               0.34.0             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rich                      13.7.1             pyhd8ed1ab_0    conda-forge
rpds-py                   0.18.0           py39hcf47035_0    conda-forge
scikit-image              0.22.0           py39h5d65943_2    conda-forge
scikit-learn              1.4.2            py39hf36d3f6_0    conda-forge
scipy                     1.13.0           py39h0ed1e0f_0    conda-forge
setuptools                69.5.1             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
sip                       6.7.12           py39h110ca85_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                h6dc393e_1    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
superqt                   0.6.3              pyh9208f05_0    conda-forge
svt-av1                   2.0.0                h73e2aa4_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tbb                       2021.12.0            h7728843_0    conda-forge
tblib                     3.0.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.4.0              pyhc1e730c_0    conda-forge
tifffile                  2024.4.18          pyhd8ed1ab_0    conda-forge
tk                        8.6.13               h1abcd95_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
toolz                     0.12.1             pyhd8ed1ab_0    conda-forge
tornado                   6.4              py39ha09f3b3_0    conda-forge
tqdm                      4.66.2             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typer                     0.12.3             pyhd8ed1ab_0    conda-forge
typer-slim                0.12.3             pyhd8ed1ab_0    conda-forge
typer-slim-standard       0.12.3               hd8ed1ab_0    conda-forge
typing-extensions         4.11.0               hd8ed1ab_0    conda-forge
typing_extensions         4.11.0             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
umap-learn                0.5.5            py39h6e9494a_1    conda-forge
unicodedata2              15.1.0           py39hdc70f33_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
vispy                     0.11.0           py39h225dfe9_1    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.16.0           py39ha09f3b3_0    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xyzservices               2024.4.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
zarr                      2.17.2             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.5                h93d8f39_0    conda-forge
zfp                       1.0.1                h295e98d_0    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib-ng                   2.0.7                hb7f2c08_0    conda-forge
zstd                      1.5.5                h829000d_0    conda-forge`

**Comment by Cryaaa** [comment]
Hello! 
The Points layer functionality is something that we are currently finalizing, so it will only work if you install the most current cluster plotter version (which currently is not yet on pypi due to some bugs we need to fix beforehand). 

If you want to give this possibly unstable release a try though you could install it by downloading the repository, unpacking it in a destination of your choice, navigating to the repository folder in your command line and installing it using `pip install .`

Thanks for your interest in the plugin and I hope this helps!

**Comment by rhornb** [comment]
Hey @Cryaaa , 

thanks for your quick help! I didn't realise from the documentation that this functionality was still part of the unstable release - maybe would be good to add this as a note. :) 

Best, 
Ruth

**Comment by Cryaaa** [comment]
@rhornb,
Completely agree and will do thanks for the input. If you do happen to test the current version though, we are always happy about any feedback!

**Comment by zoccoler** [comment]
Hi @rhornb , 

Sorry, @Cryaaa is right, the documentation was updated but the new release is still on the way. We are working to release it pretty soon, so I ask for your patience. I will add a note to the Readme for the time being, sorry for the confusion.

Also, the feature to load a table to the points layer from a plugin perspective is being worked out here: https://github.com/haesleinhuepf/napari-skimage-regionprops/pull/87
