### ISSUE TITLE
v0.8.0 not conda installable yet

### ISSUE THREAD

**Issue by zoccoler** [BiAPoL/napari-clusters-plotter#323]
[This PR](https://github.com/conda-forge/napari-clusters-plotter-feedstock/pull/14) must be merged in order to have this versions installable by conda/mamba. 

I don't have write access to that repository to merge it.

**Comment by zoccoler** [comment]
@lazigu @haesleinhuepf maybe one of you could merge it? or give other contributors here write access there?

**Comment by lazigu** [comment]
@zoccoler I merged it:) Unfortunately, I don't have access to give access to more people there, maybe @goanpeca could do it

**Comment by zoccoler** [comment]
Thank you @lazigu !!
