### ISSUE TITLE
Selecting data points doesn't work anymore in ncp 0.2.1

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#35]
Hi Laura @lazigu, hi all,

I was just excited about the new version and tested it. Unfortunately, selecting data points in the plot doesn't work anymore. :-(

Here is what I did:
* Install napari, napari-clusters-plotter, napari-segment-blobs-and-things-with-membranes, napari-pyclesperanto-assistant
* I opened `File > open examles > clesperanto > blobs (from ImageJ)`
* I segmented it using `Tools > Segmentation / labeling > Voronoi Otsu Labeling (nsbatwm)` using paramerters spot_sigma=4 and outline_sigma=2.
* I measured the properties of these blobs using napari-clusters-plotter`Measure now (with neighborhood data)`
* I started the plotter from the menu `Tools > Measurement > Plot Measurements (ncp)` and selected `area` versus `mean intensity` as shown in this video:

https://user-images.githubusercontent.com/12660498/147076112-9108ec36-8de1-4265-b76b-5d8830cc0bd1.mp4

As you can see, the selection of data points doesn't work anymore. Let me know if there is anything I can do to help fixing it. :-)

Best,
Robert

**Comment by haesleinhuepf** [comment]
Update: It was my fault! :-)

It does work in the current napari release 0.4.12, but it does not work in the current development branch (napari-0.4.13.dev139+g3069f2dc). Thus, forget what I said. We just need to check everything carefully when the next napari release is in sight.

Happy Holidays!
Robert

**Comment by lazigu** [comment]
Hi Robert @haesleinhuepf ,

Ahh thanks a lot! Scared me for a second that this new release is with such a major bug even though I thought I tested it thoroughly :D
We will keep it in mind for the next napari release then!

Happy holidays to you too!
Laura

**Comment by haesleinhuepf** [comment]
Sorry for the scaring second :-)

**Comment by lazigu** [comment]
No worries! Let me know if there are any other bugs that I might have missed :)

**Comment by haesleinhuepf** [comment]
I'm reopening this issue because it doesn't work in napari 0.4.13rc1, which was just published. I think we still have some days until napari 0.4.13 releases. Hence, not super urgent. But we should dig into this... :-)

Try it out using

```
pip install napari==0.4.13rc1
```

@lazigu @Cryaaa @zoccoler

**Comment by lazigu** [comment]
Thanks a lot for letting me know, Robert @haesleinhuepf.
I will get to work on it today or tomorrow.
