### ISSUE TITLE
allow user to give a name to a clustering result

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#68]
I just hit a little issue: If I wanted to compare combinations of dimensionality reduction + clustering, I can't store all combinations in the same table, because I can't choose the name of result columns of the clustering. E.g. I wanted to combine
* PCA + KMeans
* PCA + HDBSCAN
* UMAP + KMeans
* UMAP + HDBSCAN

I think it would be nice if we could change the result table column name, e.g. "my_custom_PCA_KMeans_CLUSTER_ID".

**Comment by haesleinhuepf** [comment]
Good point! Let's wait for things to be merged and then tackle this.

No hurry though. The next release will be amazing and we should take our time :-)

**Comment by lazigu** [comment]
I tackled this in #44 as I was working with that code part anyway, I hope it´s ok. So my solution is that there is an editable part, which by default would be the selected algorithm name (displayed as a place holder text) and non-editable part, displayed just for clarification:

![image](https://user-images.githubusercontent.com/52177660/160909847-0c6fe828-c10e-45cc-82d2-5eef1b6d0cae.png)

I´m open to suggestions if you think it could look like differently :)

**Comment by haesleinhuepf** [comment]
I love it, Laura @lazigu ! 😃

**Comment by lazigu** [comment]
I should maybe split it to a different PR, so it comes with a next release, not with a multithreading release. I will do it it tomorrow :)

**Comment by lazigu** [comment]
Hi Robert @haesleinhuepf, Rayn @Cryaaa, in your opinion, would there be a need to also save manual clustering results with different column names or should this feature just be for the clustering widget?
