### ISSUE TITLE
Remove pyclesperanto prototype from dependencies

### ISSUE THREAD

**Issue by Cryaaa** [BiAPoL/napari-clusters-plotter#81]
- [ ] We could generate the cluster image with numpy IF pyclesperanto is not installed (it might also be possible to do the dictionary colormapping visualisation on a per timepoint basis). 
- [x] Furthermore we should move measurement out of the plugin in general.

**Comment by haesleinhuepf** [comment]
The measurements are already available in [napari-pyclesperanto-assistant](). I was just adding timelapse-support there. A release is imminent.

![image](https://user-images.githubusercontent.com/12660498/166109500-16b9030e-913e-44b1-849f-77b0765d46fe.png)

**Comment by haesleinhuepf** [comment]
> We could generate the cluster image with numpy IF pyclesperanto is not installed

This function may be helpful:
https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/master/napari_skimage_regionprops/_parametric_images.py#L5

It uses pyclesperanto as optional dependency and numpy otherwise.

**Comment by Cryaaa** [comment]
@haesleinhuepf, awesome! I just have to take a quick look at our functions and see how directly we can implement this version instead!

**Comment by haesleinhuepf** [comment]
Btw. the measurements are already available in napari-pyclesperanto-assistant:
https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/ad72ecae7d017ba63f579f05dd00be627f36e89b/napari_pyclesperanto_assistant/_advanced_statistics.py#L9

Thus, we can safely remove the measurements from the clusters plotter.

The only thing that's still there is replacing this section:
https://github.com/BiAPoL/napari-clusters-plotter/blob/a9754a310b790367d42df2727de050a5cfcec0a6/napari_clusters_plotter/_utilities.py#L125

By reusing this function:
* `napari_skimage_regionprops.relabel(labels, measurements)`
https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/master/napari_skimage_regionprops/_parametric_images.py#L23

**Comment by haesleinhuepf** [comment]
Hey Ryan @Cryaaa ,

I just saw this commit: https://github.com/BiAPoL/napari-clusters-plotter/commit/a31a986449e0e77221608b264d6cb340742d1adf

Note that very similar functionality already exists here: https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/master/napari_skimage_regionprops/_load_csv.py

Let me know if we should change something there. Also how about a coffee at Katja's next week to catch up? 😉

**Comment by Cryaaa** [comment]
@haesleinhuepf,
just as I recieved your comment I realised that I should have looked there to see if the function is already implemented *facepalm*. I'm all for reusing so I'll revert this commit again. I could come this week or next week, whatever is best for you, I'm free this week but next week I'll start with Jesse but I'm sure I could find some time!
