### ISSUE TITLE
Add documentation and Prepare Release

### ISSUE THREAD

**Issue by Cryaaa** [BiAPoL/napari-clusters-plotter#84]
I have merged the timelapse PR but before we can release a new version we should update the Documentation and files:

- [x] New release version (with some backward compatibility breaking changes
Documentation:
- [x] Timelapse Measurement
- [x] How to deal with 2D timelapse data
- [x] Example timelapse data processing (possibly some movies generated by @haesleinhuepf in #77)
- [x] Reevaluate old chapters and see if they are still accurate

**Comment by Cryaaa** [comment]
@haesleinhuepf: You had suggested a 2D timelapse dataset where it is easy to see what is going on during the timelapse, which we could use for making a few demo videos. Could you send me a link to it so I can prepare some graphics?

**Comment by haesleinhuepf** [comment]
In case clesperanto is installed in napari, you find it under `File > Open examples > clesperanto > CalibZAPWfixed" and you need to use `Tools > Utilities > Convert 3D stack to 2D+t timelapse (time-slicer)` before you can pull it through measurements over time.

**Comment by Cryaaa** [comment]
@haesleinhuepf thanks a lot!

**Comment by haesleinhuepf** [comment]
@Cryaaa you can use [this notebook](https://haesleinhuepf.github.io/BioImageAnalysisNotebooks/33_batch_processing/14_process_timelapse.html) to create a compatible label image...
