### ISSUE TITLE
Missing troubleshooting information

### ISSUE THREAD

**Issue by jo-mueller** [BiAPoL/napari-clusters-plotter#86]
Hi all,

I ran into an issue recently regarding installing GPU functionality on Mac - which should be covered by the info in the Readme in the troubleshooting section. However, this did not work for that particular device (maybe newer Mac devices require a different wrapper for opencl functionality?)

Anyway, installing [this package](https://anaconda.org/conda-forge/ocl_icd_wrapper_apple) fixed it.

**Comment by haesleinhuepf** [comment]
Correct! See also installation instructions [here](https://github.com/haesleinhuepf/devbio-napari#installation)
