### ISSUE TITLE
Update list of available features in Dimensionality Reduction and Clustering widgets

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#90]
We just discussed in the napari-community meeting, there should be an event thrown (something like `layer.features.update`), we could use to update the list of features. 

To update events, this might be useful: https://github.com/napari/napari/pull/3802

@jni said, if this doesn't work, we should create an issue and it might be fixed in the upcoming napari 0.4.16. Thus, this has high priority.

CC @jo-mueller

**Comment by jni** [comment]
Here's one issue: labels doesn't have a features event (does it have features?):

```
 $ git grep events.features
examples/bbox_annotator.py:        shapes_layer.events.features()
examples/bbox_annotator.py:    shapes_layer.events.features.connect(shapes_layer.refresh_text)
napari/layers/points/points.py:        self.events.features()
napari/layers/points/points.py:            self.events.features()
napari/layers/shapes/shapes.py:        self.events.features()
napari/layers/shapes/shapes.py:            self.events.features()
napari/layers/vectors/vectors.py:        self.events.features()
```

**Comment by haesleinhuepf** [comment]
@jni Labels are the only layers, where features are relevant to us 😱

**Comment by Cryaaa** [comment]
@haesleinhuepf and @jni, thanks for the input guys! I have found out that for the labels layer an event is thrown for properties when features are set so maybe we can use this event instead?  Here is the napari code for feature setter in layers.py 
```python
    @features.setter
    def features(
        self,
        features: Union[Dict[str, np.ndarray], pd.DataFrame],
    ) -> None:
        self._feature_table.set_values(features)
        self._label_index = self._make_label_index()
        self.events.properties()
```
whereas for the points layer it is slightly different calling an event for properties and features (from napari points.py)
```python
    @features.setter
    def features(
        self,
        features: Union[Dict[str, np.ndarray], pd.DataFrame],
    ) -> None:
        self._feature_table.set_values(features, num_data=len(self.data))
        self._update_color_manager(
            self._face, self._feature_table, "face_color"
        )
        self._update_color_manager(
            self._edge, self._feature_table, "edge_color"
        )
        self.text.refresh(self.features)
        self.events.properties()
        self.events.features()
```

maybe it is as simple as suggesting to add this line for the labels layer? I will try to get the automatic updating done with the properties events but if you would agree with the change I can send a PR to the napari team adding this line aswell

**Comment by Cryaaa** [comment]
Small update: It works with the properties event

**Comment by Cryaaa** [comment]
with the next napari update also the labels layer will fire an event so I can cose this thread now!
