### ISSUE TITLE
Drawn outline doesn't go away after drawing

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/napari-clusters-plotter#95]
In the clusters plotter 0.5.0, when I draw an outline around data points and release the mouse, the blue outline of the drawing remains. I _think_ this is a new bug:

![image](https://user-images.githubusercontent.com/12660498/166927384-e7505e46-cc0d-4ee5-bd51-3e863053527c.png)

**Comment by lazigu** [comment]
@haesleinhuepf Do you still sometimes encounter this bug? I haven't been able to reproduce it

**Comment by haesleinhuepf** [comment]
I presume this has been fixed long ago 🌞
